import { createTheme, NextUIProvider } from "@nextui-org/react";
import { type Session } from "next-auth";
import { SessionProvider } from "next-auth/react";
import { type AppType } from "next/app";
import Head from "next/head";
import { NavBar } from "~/components/NavBar";
import "~/styles/globals.css";
import { api } from "~/utils/api";

const theme = createTheme({
  type: "dark",
  theme: {
    colors: {
      background: "#1e2225",
    },
  },
});

const App: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
      <Head>
        <title>Sistema de Censo</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NextUIProvider theme={theme}>
        <NavBar />
        <Component {...pageProps} />
      </NextUIProvider>
    </SessionProvider>
  );
};

export default api.withTRPC(App);
